mcp:
  servers:
    nmap:
      command: "python"
      args: ["nmap_mcp_server.py"]
    nuclei:
      command: "python"
      args: ["nuclei_mcp_server.py"]
    metasploit:
      command: "python"
      args: ["metasploit_mcp_server.py"]

logger:
  # "none", "console", "file", or "http"
  type: "file"
  # "debug", "info", "warning", or "error"
  level: "debug"
  # Enable/disable progress display
  progress_display: true
  # Path to log file (for "file" type)
  path: "fastagent.jsonl"
  # Events to accumulate before processing
  batch_size: 100
  # Flush interval in seconds
  flush_interval: 2.0
  # Maximum queue size for events
  max_queue_size: 2048
  # -----------------------
  # Console display options
  # -----------------------
  # Show chat messages on console
  show_chat: true  
  # Show MCP Server tool calls on console
  show_tools: true
  # Truncate long tool calls in display
  truncate_tools: false
  # Disable if outputs conflict with rich library markup
  enable_markup: true
  # enable the < 0.2.43 display
  use_legacy_display: false
