from langchain_google_genai import GoogleGenerativeAI, HarmCategory, HarmBlockThreshold
from langchain.agents import create_react_agent, AgentExecutor
from langchain_community.agent_toolkits import NLAToolkit, OpenAPIToolkit
from langchain import hub
import readline
import os

llm = GoogleGenerativeAI(model="gemini-pro",temperature=0)

toolkit = NLAToolkit.from_llm_and_url(llm, "https://raw.githubusercontent.com/APIs-guru/unofficial_openapi_specs/master/xkcd.com/1.0.0/openapi.yaml")
tools = toolkit.get_tools()
base_prompt = hub.pull("langchain-ai/react-agent-template")
prompt = base_prompt.partial(instructions="Answer the user's request")
agent = create_react_agent(llm,tools,prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

print("Welcome to my XKCD API application. I am configured with these tools generated by the NLAToolkit:")
for tool in agent_executor.tools:
  print(f'  Tool: {tool.name} = {tool.description} and {tool}')

while True:
    line = input("llm>> ")
    if line:
        try:
            result = agent_executor.invoke({"input":line})
            print(result)
        except Exception as e:
            print(e)
    else:
        break
