import os
import readline
from langchain.agents import create_agent
from langchain.messages import HumanMessage
from langchain_experimental.tools import PythonREPLTool
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model=os.getenv("GOOGLE_MODEL"))
#from langchain_openai import ChatOpenAI
#llm = ChatOpenAI(model=os.getenv("OPENAI_MODEL"))
#from langchain_anthropic import ChatAnthropic
#llm = ChatAnthropic(model=os.getenv("ANTHROPIC_MODEL"))

tools = [PythonREPLTool()]

system_prompt = """You are an agent designed to write and execute python code to answer
      questions.  You have access to a python REPL, which you can use to
      execute Python code.  If you get an error, debug your code and try
      again.  Only use the output of your code to answer the question.  You
      might know the answer without running any code, but you should still
      run the code to get the answer.  If it does not seem like you can
      write code to answer the question, just return I don't know as the
      answer.\n\n"""

agent = create_agent(model=llm, tools=tools, system_prompt=system_prompt)

print(f"Welcome to my application.  I am configured with these tools")
for tool in tools:
  print(f'  Tool: {tool.name} = {tool.description}')

print("Example prompt: Sort the list 12, 35, 40, 22, 10, 3.   Then see if the third largest number is prime")

while True:
    try:
        line = input("llm>> ")
        if line:
            # Stream the steps and print them as they occur
            for step in agent.stream({"messages": [{"role": "user", "content": line}]}):
                # 1. Detect Tool Calls (generated by the Model)
                if "model" in step:
                    message = step["model"]["messages"][0]
                    if message.content:
                        print(f"🛠️   Content: {message.content}")
                    if message.tool_calls:
                        for tool_call in message.tool_calls:
                            print(f"🛠️ Tool Call: {tool_call['name']}   Args: {tool_call['args']}")

                # 2. Detect Tool Results (returned by the Tools)
                if "tools" in step:
                    message = step["tools"]["messages"][0]
                    print(f"✅ Tool Result: {message.content}")
                    print("---")

                continue
        else:
            break
    except Exception as e:
        print(e)
