import os
import readline
from langchain.agents import create_agent
from langchain.messages import HumanMessage
from langchain_community.agent_toolkits.load_tools import load_tools
from langchain_experimental.tools import PythonREPLTool

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model=os.getenv("GOOGLE_MODEL"))
#from langchain_openai import ChatOpenAI
#llm = ChatOpenAI(model=os.getenv("OPENAI_MODEL"))
#from langchain_anthropic import ChatAnthropic
#llm = ChatAnthropic(model=os.getenv("ANTHROPIC_MODEL"))

tools = load_tools(["serpapi", "llm-math","wikipedia","terminal"], llm=llm, allow_dangerous_tools=True)
system_prompt = "Answer the user's request utilizing at most 8 tool calls"

agent = create_agent(model=llm, tools=tools, system_prompt=system_prompt)

print(f"Welcome to my application.  I am configured with these tools")
for tool in tools:
  print(f'  Tool: {tool.name} = {tool.description}')

print("Example prompt: Find the sum of all of the points scored in the last 2 Super Bowls")

while True:
    try:
        line = input("llm>> ")
        if line:
            # Stream the steps and print them as they occur
            for step in agent.stream({"messages": [{"role": "user", "content": line}]}):
                #print(step)
                # 1. Detect Tool Calls (generated by the Model)
                if "model" in step:
                    message = step["model"]["messages"][0]
                    if message.content:
                        print(f"🛠️  Content: {message.content}")
                    if message.tool_calls:
                        for tool_call in message.tool_calls:
                            print(f"🛠️  Tool Call: {tool_call['name']}   Args: {tool_call['args']}")

                # 2. Detect Tool Results (returned by the Tools)
                if "tools" in step:
                    message = step["tools"]["messages"][0]
                    print(f"✅ Tool Result: {message.content}")
                    print("---")
                continue
        else:
            break
    except Exception as e:
        print(e)
