import os
import readline
import validators
import dns.resolver, dns.reversename
from pydantic import BaseModel, Field, model_validator
from langchain.agents import create_agent
from langchain_community.agent_toolkits.load_tools import load_tools
from langchain.tools import tool
#from langsmith import Client
#os.environ["LANGCHAIN_TRACING_V2"] = "true"
#os.environ["LANGCHAIN_PROJECT"] = f"LangSmith Introduction"
#os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
#client = Client()
from langchain_google_genai import ChatGoogleGenerativeAI, HarmCategory, HarmBlockThreshold
llm = ChatGoogleGenerativeAI(
           model=os.getenv("GOOGLE_MODEL"),
           safety_settings = { HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE, }
)
#from langchain_openai import ChatOpenAI
#llm = ChatOpenAI(model=os.getenv("OPENAI_MODEL"))
#from langchain_anthropic import ChatAnthropic
#llm = ChatAnthropic(model=os.getenv("ANTHROPIC_MODEL"))

class LookupNameInput(BaseModel):
    hostname: str = Field(description="Should be a hostname such as www.google.com")
    @model_validator(mode="before")
    def is_dns_address(cls, values: dict[str,any]) -> dict[str,any]:
        if validators.domain(values.get("hostname")):
            return values
        raise ValueError("Malformed hostname")

@tool("lookup_name",args_schema=LookupNameInput, return_direct=False)
def lookup_name(hostname):
    """Given a DNS hostname, it will return its IPv4 addresses"""
    result = dns.resolver.resolve(hostname, 'A')
    res = [ r.to_text() for r in result ]
    return res[0]

class LookupIPInput(BaseModel):
    address: str = Field(description="Should be an IP address such as 208.91.197.27 or 143.95.239.83")
    @model_validator(mode="before")
    def is_ip_address(cls, values: dict[str,any]) -> dict[str,any]:
        if validators.ip_address.ipv4(values.get("address")):
            return values
        raise ValueError("Malformed IP address")

@tool("lookup_ip", args_schema=LookupIPInput, return_direct=False)
def lookup_ip(address):
    """Given an IP address, returns names associated with it"""
    n = dns.reversename.from_address(address)
    result = dns.resolver.resolve(n, 'PTR')
    res = [ r.to_text() for r in result ]
    return res[0]
    
tools = load_tools(["serpapi", "terminal"], allow_dangerous_tools=True)
tools.extend([lookup_name, lookup_ip])
                                                                                
system_prompt = """You are an agent designed to lookup names and addresses.
      Answer the user's request utilizing at most 8 tool calls.\n\n"""                                                            
                                                                                
agent = create_agent(model=llm, tools=tools, system_prompt=system_prompt) 

print("Welcome to my DNS and IP address lookup application. I am configured with these tools:")
for tool in tools:
  print(f'  Tool: {tool.name} = {tool.description}')

while True:                                                                     
    try:                                                                        
        line = input("llm>> ")                                                  
        if line:                                                                
            # Stream the steps and print them as they occur                     
            for step in agent.stream({"messages": [{"role": "user", "content": line}]}):
                # 1. Detect Tool Calls (generated by the Model)                 
                if "model" in step:                                             
                    message = step["model"]["messages"][0]                      
                    if message.content:                                         
                        print(f"🛠️    Content: {message.content}")               
                    if message.tool_calls:                                      
                        for tool_call in message.tool_calls:                    
                            print(f"🛠️  Tool Call: {tool_call['name']}   Args: {tool_call['args']}")
                                                                                
                # 2. Detect Tool Results (returned by the Tools)                
                if "tools" in step:                                             
                    message = step["tools"]["messages"][0]                      
                    print(f"✅ Tool Result: {message.content}")                 
                    print("---")                                                
                                                                                
                continue                                                        
        else:                                                                   
            break                                                               
    except Exception as e:                                                      
        print(e)
