mcp:
  servers:
    nmap:
      command: "python"
      args: ["nmap_mcp_server.py"]
    opencve:
      command: "python"
      args: ["opencve_mcp_server.py"]
      env:
        OPENCVE_USERNAME: "${OPENCVE_USERNAME}"
        OPENCVE_PASSWORD: "${OPENCVE_PASSWORD}"
    nuclei:
      command: "python"
      args: ["nuclei_mcp_server.py"]
    metasploit:
      command: "python"
      args: ["metasploit_mcp_server.py"]
    hashcat:
      command: "python"
      args: ["hashcat_mcp_server.py"]
    gobuster:
      command: "python"
      args: ["gobuster_mcp_server.py"]
    curl:
      command: "python"
      args: ["curl_mcp_server.py"]
    sqlmap:
      command: "python"
      args: ["sqlmap_mcp_server.py"]
    filesystem:
      command: "python"
      args: ["filesystem_mcp_server.py"]