mcp:
  servers:
    nmap:
      command: "python"
      args: ["nmap_mcp_server.py"]
    nuclei:
      command: "python"
      args: ["nuclei_mcp_server.py"]
    metasploit:
      command: "python"
      args: ["metasploit_mcp_server.py"]
